version: '3.8'
services:
  flask-app:
    image: soham444/therabot:latest
    container_name: therabot_flask_app
    ports:
      - "8000:8000"
    env_file:
      - .env

    restart: on-failure:3
    healthcheck:
      test: ["CMD","curl", "-f","http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3


