apiVersion: v1
kind: Service
metadata:
  name: therabot-k3s-service
  namespace: development
spec:
  selector:
    app: therabot-k3s
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
  type: NodePort